apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: edge
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: "VerySecretPassword"
      write_files:
      - content: |
          OPTION1="yes"
          OPTION2="false"
        path: "/etc/myservice.conf"
      runcmd:
      - mkdir -p /usr/local/data
      - mount /dev/disk/by-label/EXTRA_PART /usr/local/data
    elemental:
      install:
        reboot: true
        device: /dev/vda
        debug: true
        config-dir: /etc/elemental
  machineInventoryLabels:
    cores: "${System Data/CPU/Total Cores}"
    memory: "${System Data/Memory/Total Physical Bytes}"
    registration: edge
